### ISSUE TITLE
brd_safety_deflt must be set to 0

### ISSUE THREAD

**Issue by slovak194** [Drone-Volt/ardupilot#4]
## Bug report

>> The ESCs are beeping, that's because they don't receive a pwn signal, that's because there is a parameter that must be set to 0 brd_safety_deflt, that is the Safety switch on startup

This needs to be checked.

**Comment by slovak194** [comment]
Fixed in slovak-dev branch. Issue will be closed after successful flight test.

**Comment by DaanAT** [comment]
BRD_SAFETY_DELFT = 0 is correct.

**Comment by slovak194** [comment]
Confirmed as fixed.
