### ISSUE TITLE
GPS_TYPE params are missing in the default parameter list

### ISSUE THREAD

**Issue by slovak194** [Drone-Volt/ardupilot#5]
GPS_TYPS are missing from the default parameter list.

GPS_TYPE 17
GPS_TYPE2 18

**Comment by slovak194** [comment]
Fixed in slovak-dev branch. Issue will be closed after successful flight test.

**Comment by DaanAT** [comment]
GPS_TYPE 17
GPS_TYPE2 18

Is correct

**Comment by slovak194** [comment]
Confirmed as fixed.
