### ISSUE TITLE
Servo functions are wrong for 9, 10, 11, 12

### ISSUE THREAD

**Issue by slovak194** [Drone-Volt/ardupilot#6]
From Eder.
Must be set to:
SERVO9_FUNCTION 33
SERVO10_FUNCTION 34
SERVO11_FUNCTION 35
SERVO12_FUNCTION 36

**Comment by slovak194** [comment]
Fixed in slovak-dev branch. Issue will be closed after successful flight test.

**Comment by DaanAT** [comment]
You can close this. 

SERVO9_FUNCTION 33
SERVO10_FUNCTION 34
SERVO11_FUNCTION 35
SERVO12_FUNCTION 36

Are correct.

**Comment by slovak194** [comment]
Confirmed as fixed.
